[package]
name = "video_viewer"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/video_viewer.rs"
doctest = false

[dependencies]
anyhow.workspace = true
db.workspace = true
file_icons.workspace = true
gpui.workspace = true
image.workspace = true
language.workspace = true
log.workspace = true
project.workspace = true
serde.workspace = true
settings.workspace = true
theme.workspace = true
ui.workspace = true
util.workspace = true
workspace.workspace = true
parking_lot = "0.12"
smallvec = "1"
gstreamer = "0.24"
gstreamer-app = "0.24"
gstreamer-video = "0.24"
glib = "0.21"
